---
AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable         # enable new upcoming cops for rubocop
  Exclude:
    - _snippets/**/*

plugins:
  - rubocop-minitest

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*