---
# COPY this file to secrets.yml and modify as needed
development:
  DATABASE_URL: sqlite://db/local/development.db
  DB_KEY: dGVzdF9rZXlfZm9yX3NlY3VyaXR5 # Base64 encoded string
  TICKET_SALT: dGVzdF9zYWx0X2Zvcl90aWNrZXRz # Base64 encoded string

test:
  DATABASE_URL: sqlite://db/local/test.db
  DB_KEY: dGVzdF9rZXlfZm9yX3NlY3VyaXR5 # Base64 encoded string
  TICKET_SALT: dGVzdF9zYWx0X2Zvcl90aWNrZXRz # Base64 encoded string

production:
  DATABASE_URL: sqlite://db/local/production.db
  DB_KEY: dGVzdF9rZXlfZm9yX3NlY3VyaXR5 # Base64 encoded string
  TICKET_SALT: dGVzdF9zYWx0X2Zvcl90aWNrZXRz # Base64 encoded string
