---
# COPY this file to secrets.yml and modify as needed
# DO NOT PUT ANY SENSITIVE DATA IN THIS FILE
# otherwise public execution
development:
  DATABASE_URL: sqlite://db/local/development.db
  DB_KEY: some_secure_key # Base64 encoded string
  MSG_KEY: some_secure_key # Base64 encoded string
  SECURE_SCHEME: HTTP
  MAIL_API_KEY: < get from Brevo >
  MAIL_SENDER: < should be verified by Brevo >

test:
  DATABASE_URL: sqlite://db/local/test.db
  DB_KEY: some_secure_key # Base64 encoded string
  MSG_KEY: some_secure_key # Base64 encoded string
  SECURE_SCHEME: HTTP
  MAIL_API_KEY: < get from Brevo >
  MAIL_SENDER: < should be verified by Brevo >

production:
  DATABASE_URL: < heroku PG addone>
  DB_KEY: some_secure_key # Base64 encoded string
  MSG_KEY: some_secure_key # Base64 encoded string
  SECURE_SCHEME: HTTPS
  MAIL_API_KEY: < get from Brevo >
  MAIL_SENDER: < should be verified by Brevo >
