---
# COPY this file to secrets.yml and modify as needed
# DO NOT PUT ANY SENSITIVE DATA IN THIS FILE
# otherwise public execution
development:
  DATABASE_URL: sqlite://db/local/development.db
  API_HOST: http://localhost:3000
  DB_KEY: some_secure_key # Base64 encoded string
  SIGNING_KEY: some_secure_key
  VERIFY_KEY: some_secure_key
  MSG_KEY: some_secure_key # Base64 encoded string
  SECURE_SCHEME: HTTP
  MAIL_API_KEY: < get from Brevo >
  MAIL_SENDER: < should be verified by Brevo >
  GOOGLE_ACCOUNT_URL: https://www.googleapis.com/oauth2/v3/userinfo
  GOOGLE_GEO_KEY: < get from Google >

test:
  DATABASE_URL: sqlite://db/local/test.db
  API_HOST: http://localhost:3000
  DB_KEY: some_secure_key # Base64 encoded string
  SIGNING_KEY: some_secure_key
  VERIFY_KEY: some_secure_key
  MSG_KEY: some_secure_key # Base64 encoded string
  SECURE_SCHEME: HTTP
  MAIL_API_KEY: < get from Brevo >
  MAIL_SENDER: < should be verified by Brevo >
  GOOGLE_ACCOUNT_URL: https://www.googleapis.com/oauth2/v3/userinfo
  GOOGLE_GEO_KEY: < get from Google >

production:
  DATABASE_URL: < heroku PG addone>
  DB_KEY: some_secure_key # Base64 encoded string
  SIGNING_KEY: some_secure_key
  VERIFY_KEY: some_secure_key
  MSG_KEY: some_secure_key # Base64 encoded string
  SECURE_SCHEME: HTTPS
  MAIL_API_KEY: < get from Brevo >
  MAIL_SENDER: < should be verified by Brevo >
  GOOGLE_ACCOUNT_URL: https://www.googleapis.com/oauth2/v3/userinfo
  GOOGLE_GEO_KEY: < get from Google >
