---
# COPY this file to secrets.yml and modify as needed
# DO NOT PUT ANY SENSITIVE DATA IN THIS FILE
# otherwise public execution
development:
  DATABASE_URL: sqlite://db/local/development.db
  DB_KEY: some_secure_key # Base64 encoded string
  SECURE_SCHEME: HTTP

test:
  DATABASE_URL: sqlite://db/local/test.db
  DB_KEY: some_secure_key # Base64 encoded string
  SECURE_SCHEME: HTTP

production:
  DATABASE_URL: sqlite://db/local/production.db
  DB_KEY: some_secure_key # Base64 encoded string
  SECURE_SCHEME: HTTPS
